# Generated by Django 5.0.7 on 2024-08-04 12:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('habit_is_pleasant', models.BooleanField(default=True, verbose_name='Good habit')),
                ('number_of_executions', models.IntegerField(default=1, verbose_name='Number of actions per week')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Duration of habit')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is habit published')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reward')),
                ('connection_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Connected habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
